### ISSUE TITLE
minimize package dependencies

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.install#4]
move `data.table` and `Require` to Suggests?

**Comment by eliotmcintire** [comment]
I tried. We can't. The `makeSure...` function recovers an object from a previous `Require` call that _is_ a `data.table`. Just to look at that object, we need `data.table`. So, unless I rework `Require` to _not use_ `data.table` package, these both will be an `Imports` here.

**Comment by achubaty** [comment]
thanks for taking a look. i suspected as much
