### ISSUE TITLE
add to drat for simpler install

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.install#6]

**Comment by achubaty** [comment]
done with https://github.com/PredictiveEcology/drat/commit/c2ef233c4a8caac73c992bb47764da3f7c84bb07

**Comment by achubaty** [comment]
@eliotmcintire this should help with package install. can you please update `README` accordingly?

**Comment by eliotmcintire** [comment]
@achubaty What is the "binary" upload schedule?

**Comment by achubaty** [comment]
rebuilt with the GHA workflow:
- weekly (Monday) morning
- on push when a change is made to the `packages.txt`, `build_binaries.R`, or `build-packages.yaml` files

See https://github.com/PredictiveEcology/drat/blob/main/.github/workflows/build-packages.yaml#L1-L8

**Comment by achubaty** [comment]
i just did maunal rebuilds in the last hour or so, because there's a fun 'glitch' in the setup that I know about but can't resolve atm

**Comment by achubaty** [comment]
@eliotmcintire if you run the `build_binaries.R` file yourself you can manually add latest versions.
